### ISSUE TITLE
Need help running behind reverse proxy (traefik)

### ISSUE THREAD

**Issue by ovizii** [r7wx/easy-gate#5]
Hi there,

I run plenty of little apps behind a reverse proxy but I can't get this one working. I might be too dumb to follow your instructions to run easy-gate behind a configured nginx which I assume applies to running it behind a configured traefik too? 

Here is where I'm stuck:

accessing easy-gate directly works fine: http://10.10.10.10:8080/ but as soon as I access it via my reverse proxy: https://my.domain.tld I get this error:

```
{
	"Message": "no app for hostname",
	"Host": "my.domain.tld",
	"Detail": "Check the outpost settings and make sure 'my.domain.tld' is included."
}
```

I searched the code on this site for the word outpost and later for the word hostname without any hits so I am at a loss as to where and how exactly to tell easy-gate that it may respond to my.domain.tld :-/ 

Any help is much appreaciated.

**Comment by dzonerzy** [comment]
This does not seems to be related to easy-gate itself , just wait for the develop branch to be merged and running behind a reverse proxy will be easier.

**Comment by ovizii** [comment]
:-( I must have had a blonde moment. I wasted 2 hours yesterday looking all over the code of easy-gate to figure it out all-the-while the problem was sitting in front of the keyboard: I had popped easy-gate behind authentik authentication. That was where the message came from as I had not finished the configuration.

Everything works perfectly now. Sorry for wasting your time.

**Comment by fabwebdev** [comment]
Can you please share your docker file with me? I'm newbie and trying to set it up with traefik and docker

**Comment by ovizii** [comment]
I don't have a Dockerfile but if you meant my docker-compose.yml file here it is:

```
version: '3.9'                                                                                                                                       
                                                                                                                                                     
# https://github.com/r7wx/easy-gate                                                                                                                  
# get more icons: https://fontawesome.com/icons                                                                                                      
                                                                                                                                                     
services:                                                                                                                                            
  easy-gate:                                                                                                                                         
    image: r7wx/easy-gate:latest                                                                                                                        
    container_name: easy-gate                                                                                                                        
    hostname: easy-gate                                                                                                                              
    volumes:                                                                                                                                         
      - ./easy-gate.json:/etc/easy-gate/easy-gate.json                                                                                               
    restart: "no"                                                                                                                                    
    environment:                                                                                                                                     
      - TZ=Europe/Berlin                                                                                                                             
    networks:                                                                                                                                        
      - traefik                                                                                                                                      
    labels:                                                                                                                                          
      - "traefik.enable=true"                                                                                                                        
      - "traefik.docker.network=traefik"                                                                                                             
      - "traefik.http.routers.gate.tls=true"                                                                                                         
      - "traefik.http.routers.gate.entrypoints=https"                                                                                                
      - "traefik.http.routers.gate.rule=Host(`sub.domain.tld`)"                                                                                       
      - "traefik.http.routers.gate.middlewares=secHeaders@file"                                                                                      
      - "traefik.http.routers.gate.service=gate"                                                                                                     
      - "traefik.http.services.gate.loadbalancer.server.port=80"                                                                                     
                                                                                                                                                     
                                                                                                                                                     
networks:                                                                                                                                            
  traefik:                                                                                                                                           
    external:                                                                                                                                        
      name: traefik                                           
```

secHeaders@file are headers I defined in a file, so I guess you can skip the whole line. Should work.
